title: "Blog EK Title"
author: "Blog EK Author"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: home}
#  - {file: "/CV.pdf", title: "CV", title: "About me", icon: address-card}
  - {title: "CV", url: "https://github.com/denawk/denawk.github.io/blob/master/assets/CV.pdf"}
  - {file: "README.md", title: "About me"}
  - {title: "Bing", url: "https://bing.com"}
  - {title: "Blog", file: "blog.md"}

## List of links in the navigation bar
# navbar-links:
#  Moi: "aboutme"
#  Projects:
#    - Hell Game: "http://deanattali.com/beautiful-jekyll/"
#    - Success City: "http://www.markdowntutorial.com/"
#  Resume: "Tech Resume.pdf"

## javascript to accomplish same as above (open file in new window/tab)
# {% include new-window-fix.html %}
# </body>
# </html>

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:denawk.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/denawk/"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
